from django.urls import path, re_path
from apitest import views
from apitest import views_tool

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('home_log/<int:id>/', views.home, name='home'),
    # re_path('child/(?P<eid>.+)/(?P<oid>.*)/$', views.child, name='child'),
    path('login/', views.login, name='login'),
    path('login_action/', views.login_action, name='login_action'),
    path('register_action/', views.register_action, name='register_action'),
    path('logout/', views.logout, name='logout'),
    path('pei/', views.pei, name='pei'),
    path('help/', views.api_help, name='api_help'),
    path('project_list/', views.project_list, name='project_list'),
    path('delete_project/', views.delete_project, name='delete_project'),
    path('add_project/', views.add_project, name='add_project'),
    path('apis/<int:id>/', views.open_apis, name='open_apis'),
    path('cases/<int:id>/', views.open_cases, name='open_cases'),
    path('add_case/<int:id>/', views.add_case, name='add_case'),
    path('del_case/<int:project_id>/<int:case_id>/', views.del_case, name='del_case'),
    path('copy_case/<int:project_id>/<int:case_id>/', views.copy_case, name='copy_case'),
    path('project_set/<int:id>/', views.open_project_set, name='open_project_set'),
    path('save_project_set/<int:id>/', views.save_project_set, name='save_project_set'),
    path('save_bz/', views.save_bz, name='save_bz'),
    path('get_bz/', views.get_bz, name='get_bz'),
    path('api_save/', views.Api_save, name='Api_save'),
    path('get_api_data/', views.get_api_data, name='get_api_data'),
    path('api_send/', views.api_send, name='api_send'),
    path('project_api_add/<int:Pid>/', views.project_api_add, name='project_api_add'),
    path('project_api_del/<int:id>/', views.project_api_del, name='project_api_del'),
    path('copy_api/', views.copy_api, name='copy_api'),
    path('error_request/', views.error_request, name='error_request'),
    path('api_send_home/', views.Api_send_home, name='Api_send_home'),
    path('get_home_log/', views.get_home_log, name='get_home_log'),
    path('get_api_log_home/', views.get_api_log_home, name='get_api_log_home'),
    path('get_small/', views.get_small, name='get_small'),
    path('user_upload/', views.user_upload, name='user_upload'),
    path('add_new_step/', views.add_new_step, name='add_new_step'),
    path('delete_step/<int:id>/', views.delete_step, name='delete_step'),
    path('get_step/', views.get_step, name='get_step'),
    path('save_step/', views.save_step, name='save_step'),
    path('step_get_api/', views.step_get_api, name='step_get_api'),
    path('Run_Case/', views.Run_Case, name='Run_Case'),
    path('look_report/<int:id>/', views.look_report, name='look_report'),
    path('tools_zhengjiao/', views_tool.zhengjiao, name='zhengjiao'),
    path('zhengjiao_play/', views_tool.zhengjiao_play, name='zhengjiao_play'),
    path('zhengjiao_excel/', views_tool.zhengjiao_excel, name='zhengjiao_excel'),
]