# Generated by Django 3.2.7 on 2021-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_db_apis_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tucao',
            name='create_time',
            field=models.DateTimeField(auto_created=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='db_tucao',
            name='text',
            field=models.CharField(max_length=1000, null=True, verbose_name='吐槽内容'),
        ),
        migrations.AlterField(
            model_name='db_tucao',
            name='user',
            field=models.CharField(max_length=30, null=True, verbose_name='吐槽人用户名'),
        ),
    ]
