# Generated by Django 3.2.7 on 2021-09-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20210915_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_tucao',
            options={'verbose_name': '吐槽内容表', 'verbose_name_plural': '吐槽内容表'},
        ),
    ]
