# Generated by Django 3.2.7 on 2021-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_alter_db_tucao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_project',
            options={'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterField(
            model_name='db_project',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='other_user',
            field=models.CharField(max_length=100, null=True, verbose_name='项目其他创建者名字'),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='remark',
            field=models.CharField(max_length=1000, null=True, verbose_name='项目备注'),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='username',
            field=models.CharField(max_length=15, null=True, verbose_name='项目创建者名字'),
        ),
    ]
