# Generated by Django 3.2.7 on 2021-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20210915_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True, verbose_name='项目id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='用例名称')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
            },
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_body',
            field=models.CharField(max_length=1000, null=True, verbose_name='请求体'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_header',
            field=models.CharField(max_length=1000, null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_host',
            field=models.CharField(max_length=100, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_login',
            field=models.CharField(max_length=10, null=True, verbose_name='是否带登陆态'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_method',
            field=models.CharField(max_length=10, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='api_url',
            field=models.CharField(max_length=1000, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='body_method',
            field=models.CharField(max_length=20, null=True, verbose_name='请求体编码格式'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='file_key',
            field=models.CharField(max_length=50, null=True, verbose_name='文件key'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='file_name',
            field=models.CharField(max_length=50, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='sign',
            field=models.CharField(max_length=10, null=True, verbose_name='是否验签'),
        ),
        migrations.AlterField(
            model_name='db_apis_log',
            name='user_id',
            field=models.CharField(max_length=10, null=True, verbose_name='所属用户id'),
        ),
    ]
