# Generated by Django 3.2.7 on 2021-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0012_auto_20210918_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_id', models.CharField(max_length=10, null=True, verbose_name='所属大用例id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='步骤名字')),
                ('index', models.IntegerField(null=True, verbose_name='执行步骤')),
                ('api_method', models.CharField(max_length=10, null=True, verbose_name='请求方式')),
                ('api_url', models.CharField(max_length=1000, null=True, verbose_name='url')),
                ('api_host', models.CharField(max_length=100, null=True, verbose_name='host')),
                ('api_header', models.CharField(max_length=1000, null=True, verbose_name='请求头')),
                ('api_body_method', models.CharField(max_length=10, null=True, verbose_name='请求体编码类型')),
                ('api_body', models.CharField(max_length=10, null=True, verbose_name='请求体')),
                ('get_path', models.CharField(max_length=500, null=True, verbose_name='提取返回值')),
                ('get_zz', models.CharField(max_length=500, null=True, verbose_name='提取返回值-正则')),
                ('assert_zz', models.CharField(max_length=500, null=True, verbose_name='断言返回值-正则')),
                ('assert_qz', models.CharField(max_length=500, null=True, verbose_name='断言返回值-全文检索存在')),
                ('assert_path', models.CharField(max_length=500, null=True, verbose_name='断言返回值-路径法')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
    ]
