# Generated by Django 3.2.7 on 2021-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0014_db_step_mock_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True, verbose_name='所属项目id')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='请求头变量名字')),
                ('key', models.CharField(max_length=20, null=True, verbose_name='请求头header的 key')),
                ('value', models.TextField(null=True, verbose_name='请求头的value，因为有可能cookie较大，达到几千字符，所以采用大文本方式存储')),
            ],
            options={
                'verbose_name': '公共请求头表',
                'verbose_name_plural': '公共请求头表',
            },
        ),
    ]
